---
- name: install mysql-server
  ansible.builtin.include_tasks:
    ansible.builtin.file: install.yml

- name: Setup zabbiz database
  ansible.builtin.include_tasks:
    ansible.builtin.file: db_zabbix.yml
