---
- name: Setup cloudflared docker container
  community.docker.docker_container:
    name: cloudflared
    state: started
    pull: false
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run
    env:
      TUNNEL_TOKEN: "{{ cloudflared_tunnel_token__gateway }}"
