---
database:
  hosts:
    database1003:
      ansible_host: 10.210.4.3

monitor:
  hosts:
    monitor1002:
      ansible_host: 10.210.2.2

cache:
  hosts:
    cache1001:
      ansible_host: 10.210.5.1

admin:
  hosts:
    admin1001:
      ansible_host: 10.210.6.1

unbound:
  hosts:
    unbound1001:
      ansible_host: 10.210.9.1

minecraft:
  hosts:
    minecraft1004:
      ansible_host: 10.210.30.4
    minecraft1005:
      ansible_host: 10.210.30.5
    minecraft1006:
      ansible_host: 10.210.30.6

minecraftv2:
  hosts:
    minecraft2001:
      ansible_host: 10.210.30.1

minecraftproxy:
  hosts:
    minecraftproxy1001:
      ansible_host: 10.210.30.101

minecraftpanel:
  hosts:
    minecraftpanel1001:
      ansible_host: 10.210.30.111

gateway:
  hosts:
    gateway1001:
      ansible_host: 10.210.3.1

honeypot:
  hosts:
    honeypot1001:
      ansible_host: 10.210.11.100
