---
- name: mkdir opt/kitsunebi directory
  file:
    path: "/opt/kitsunebi"
    state: directory
    owner: minecraft
    group: minecraft
    mode: "0755"
  become: true

- name: Git clone kitsunebi
  git:
    repo: "https://github.com/mcplaynetwork/kitsunebi.git"
    dest: "/opt/kitsunebi"
    version: "master"
  become: true
  become_user: minecraft
