---
- name: Install Zabbix Server
  ansible.builtin.apt:
    name:
      - zabbix-server-mysql
      - zabbix-frontend-php
      - fonts-ipafont-gothic
    state: present
  become: true

- name: Copy Zabbix Server Configuration
  template:
    src: ./etc/zabbix/zabbix_server.conf
    dest: /etc/zabbix/zabbix_server.conf
    owner: root
    group: root
    mode: 0644
  become: true
  notify: restart zabbix-server

- name: Create Symbolic Link
  ansible.builtin.file:
    src: /usr/share/fonts/opentype/ipafont-gothic/ipag.ttf
    dest: /usr/share/zabbix/assets/fonts/ipag.ttf
    state: link
  become: true
  notify: restart zabbix-server

- name: Replace ZBX_GRAPH_FONT_NAME
  lineinfile:
    path: /usr/share/zabbix/include/defines.inc.php
    regexp: "^define\\('ZBX_GRAPH_FONT_NAME',.*$"
    line: "define('ZBX_GRAPH_FONT_NAME', 'ipag');"
  become: true
  notify: restart zabbix-server

- name: Enable Zabbix Server
  ansible.builtin.systemd_service:
    name: zabbix-server
    enabled: true
    state: started
  become: true

- name: Install Zabbix Agent
  ansible.builtin.apt:
    name:
      - zabbix-agent2
      - zabbix-agent2-plugin-*
    state: present
  become: true

- name: Copy Zabbix Agent Configuration
  ansible.builtin.copy:
    src: ./etc/zabbix/zabbix_agent2.conf
    dest: /etc/zabbix/zabbix_agent2.conf
    owner: root
    group: root
    mode: 0644
  become: true
  notify: restart zabbix-agent2

- name: Enable Zabbix Agent
  ansible.builtin.systemd_service:
    name: zabbix-agent2
    enabled: true
    state: started
  become: true
