---
- name: Copy 20auto-upgrades
  copy:
    src: ./etc/apt/apt.conf.d/20auto-upgrades
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: 0644
  become: true
  notify: restart unattended-upgrades

- name: Copy 50unattended-upgrades
  copy:
    src: ./etc/apt/apt.conf.d/50unattended-upgrades
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root
    group: root
    mode: 0644
  become: true
  notify: restart unattended-upgrades
