---
- name: Install MySQL Server
  ansible.builtin.apt:
    name:
      - mysql-server-8.0
      - mysql-client-8.0
      - python3-pymysql
    state: present
  become: true

- name: Set MySQL Root Password
  community.mysql.mysql_user:
    login_user: "root"
    login_password: "{{ mysql_root_password }}"
    login_unix_socket: "{{ mysql_login_unix_socket }}"
    name: "root"
    password: "{{ mysql_root_password }}"
    check_implicit_admin: true
    state: present
  become: true

- name: Remove anonymous users
  community.mysql.mysql_user:
    login_user: "root"
    login_password: "{{ mysql_root_password }}"
    login_unix_socket: "{{ mysql_login_unix_socket }}"
    name: ""
    state: absent
  become: true

- name: Copy mysqld.cnf
  ansible.builtin.copy:
    src: ./etc/mysql/mysql.conf.d/mysqld.cnf
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
    owner: root
    group: root
    mode: 0644
  become: true
  notify: restart mysql

- name: Enable MySQL Service
  ansible.builtin.service:
    name: mysql
    enabled: true
    state: started
  become: true
