---
- name: Install php8.1 php8.1-{common,cli,gd,mysql,mbstring,bcmath,xml,fpm,curl,zip}
  ansible.builtin.apt:
    name:
      - php8.1
      - php8.1-common
      - php8.1-cli
      - php8.1-gd
      - php8.1-mysql
      - php8.1-mbstring
      - php8.1-bcmath
      - php8.1-xml
      - php8.1-fpm
      - php8.1-curl
      - php8.1-zip
    state: present
  become: true
