---
- name: mkdir /opt/infra-core directory
  ansible.builtin.file:
    path: "/opt/infra-core"
    state: directory
    owner: infra
    ansible.builtin.group: infra
    mode: "0755"
  become: true

- name: Git clone infra-core
  ansible.builtin.git:
    repo: "https://github.com/alflag-team/infra-core.git"
    dest: "/opt/infra-core"
    version: "master"
    update: false
  become: true
  become_user: infra
