---
- name: Copy sshd_config
  copy:
    src: ./etc/ssh/sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  become: true
  notify:
    - restart sshd

- name: Copy sshd_config.d/99-password-auth
  copy:
    src: ./etc/ssh/sshd_config.d/99-password-auth
    dest: /etc/ssh/sshd_config.d/99-password-auth
    owner: root
    group: root
    mode: 0644
  become: true
  notify:
    - restart sshd

- name: Delete sshd_config.d/60-cloudimg-settings.conf
  file:
    path: /etc/ssh/sshd_config.d/60-cloudimg-settings.conf
    state: absent
  become: true
  notify:
    - restart sshd
