---
- name: Setup admin
  hosts: admin
  ignore_unreachable: true

  roles:
    - ../../ansible-common/base
    - apt
    - python3-pip
    - infra-core
    - kitsunebi
    - ansible
    - ../../ansible-common/docker
    # - terraform
