---
- name: Install php-fpm
  ansible.builtin.apt:
    name:
      - php8.1-fpm
    state: present
  become: true

- name: Copy 99-zabbix.ini
  template:
    src: 99-zabbix.ini
    dest: /etc/php/8.1/fpm/conf.d/99-zabbix.ini
    owner: root
    group: root
    mode: 0644
  become: true
  notify: restart php8.1-fpm

- name: Enable php-fpm
  ansible.builtin.systemd_service:
    name: php8.1-fpm
    enabled: true
    state: started
  become: true
