---
- name: Install unbound
  ansible.builtin.apt:
    name:
      - unbound
    state: present
  become: true

- name: Disable systemd-resolved
  ansible.builtin.systemd:
    name: systemd-resolved
    enabled: no
    state: stopped
  become: true

- name: Enable unbound
  ansible.builtin.systemd:
    name: unbound
    enabled: yes
    state: started
  become: true

- name: Copy unbound configuration
  ansible.builtin.copy:
    src: ./etc/unbound/unbound.conf
    dest: /etc/unbound/unbound.conf
  become: true
  notify:
    - Restart unbound
