---
- name: Create pterodactyl Database
  community.mysql.mysql_db:
    login_user: "root"
    login_password: "{{ db_root_password }}"
    login_unix_socket: "{{ db_login_unix_socket }}"
    name: "{{ db_pterodactyl_database }}"
    state: present

- name: Create pterodactyl User
  community.mysql.mysql_user:
    login_user: "root"
    login_password: "{{ db_root_password }}"
    login_unix_socket: "{{ db_login_unix_socket }}"
    name: "{{ db_pterodactyl_user }}"
    password: "{{ db_pterodactyl_password }}"
    host: "10.210.30.%"
    priv: "{{ db_pterodactyl_database }}.*:ALL"
    state: present
