---
- name: Create /usr/share/keyrings
  ansible.builtin.file:
    path: /usr/share/keyrings
    state: directory
    mode: 0755
  become: true

- name: Download hashicorp gpg key
  ansible.builtin.get_url:
    url: https://apt.releases.hashicorp.com/gpg
    dest: /usr/share/keyrings/hashicorp-archive-keyring.gpg
    mode: 0644
  become: true

- name: Add hashicorp repository
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main
    state: present
  become: true

- name: Install terraform
  ansible.builtin.apt:
    name: terraform
    state: present
  become: true
