---
- name: Create infra group
  include_tasks:
    file: group-infra.yml
    apply:
      become: true

- name: Create minecraft group
  include_tasks:
    file: group-minecraft.yml
    apply:
      become: true

- name: Create docker group
  include_tasks:
    file: group-docker.yml
    apply:
      become: true
  